In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

%matplotlib inline

# Hide warnings
import warnings
warnings.filterwarnings('ignore')

In [2]:
data = pd.read_csv("DSL-StrongPasswordData.csv")

In [3]:
data.head()

subject  sessionIndex  rep  H.period  DD.period.t  UD.period.t     H.t  \
0    s002             1    1    0.1491       0.3979       0.2488  0.1069   
1    s002             1    2    0.1111       0.3451       0.2340  0.0694   
2    s002             1    3    0.1328       0.2072       0.0744  0.0731   
3    s002             1    4    0.1291       0.2515       0.1224  0.1059   
4    s002             1    5    0.1249       0.2317       0.1068  0.0895   

   DD.t.i  UD.t.i     H.i  ...     H.a  DD.a.n  UD.a.n     H.n  DD.n.l  \
0  0.1674  0.0605  0.1169  ...  0.1349  0.1484  0.0135  0.0932  0.3515   
1  0.1283  0.0589  0.0908  ...  0.1412  0.2558  0.1146  0.1146  0.2642   
2  0.1291  0.0560  0.0821  ...  0.1621  0.2332  0.0711  0.1172  0.2705   
3  0.2495  0.1436  0.1040  ...  0.1457  0.1629  0.0172  0.0866  0.2341   
4  0.1676  0.0781  0.0903  ...  0.1312  0.1582  0.0270  0.0884  0.2517   

   UD.n.l     H.l  DD.l.Return  UD.l.Return  H.Return  
0  0.2583  0.1338       0.3509       0.2171    0.0742  
1  0.1496  0.0839       0.2756       0.1917    0.0747  
2  0.1533  0.1085       0.2847       0.1762    0.0945  
3  0.1475  0.0845       0.3232       0.2387    0.0813  
4  0.1633  0.0903       0.2517       0.1614    0.0818  

[5 rows x 34 columns]

In [4]:
data.shape

(20400, 34)

In [5]:
X = data.iloc[:,3:]
y = data.iloc[:,0]

In [6]:
print(X.shape)
X.head()


(20400, 31)


H.period  DD.period.t  UD.period.t     H.t  DD.t.i  UD.t.i     H.i  DD.i.e  \
0    0.1491       0.3979       0.2488  0.1069  0.1674  0.0605  0.1169  0.2212   
1    0.1111       0.3451       0.2340  0.0694  0.1283  0.0589  0.0908  0.1357   
2    0.1328       0.2072       0.0744  0.0731  0.1291  0.0560  0.0821  0.1542   
3    0.1291       0.2515       0.1224  0.1059  0.2495  0.1436  0.1040  0.2038   
4    0.1249       0.2317       0.1068  0.0895  0.1676  0.0781  0.0903  0.1589   

   UD.i.e     H.e  ...     H.a  DD.a.n  UD.a.n     H.n  DD.n.l  UD.n.l  \
0  0.1043  0.1417  ...  0.1349  0.1484  0.0135  0.0932  0.3515  0.2583   
1  0.0449  0.0829  ...  0.1412  0.2558  0.1146  0.1146  0.2642  0.1496   
2  0.0721  0.0808  ...  0.1621  0.2332  0.0711  0.1172  0.2705  0.1533   
3  0.0998  0.0900  ...  0.1457  0.1629  0.0172  0.0866  0.2341  0.1475   
4  0.0686  0.0805  ...  0.1312  0.1582  0.0270  0.0884  0.2517  0.1633   

      H.l  DD.l.Return  UD.l.Return  H.Return  
0  0.1338       0.3509       0.2171    0.0742  
1  0.0839       0.2756       0.1917    0.0747  
2  0.1085       0.2847       0.1762    0.0945  
3  0.0845       0.3232       0.2387    0.0813  
4  0.0903       0.2517       0.1614    0.0818  

[5 rows x 31 columns]

In [7]:
print(y.shape)
y.head()

(20400,)


0    s002
1    s002
2    s002
3    s002
4    s002
Name: subject, dtype: object

In [8]:

# one hot encode y
import pandas as pd
print(y[0:2000].shape)
y_10 = pd.get_dummies(y[0:2000]).values

print(y_10.shape)
y_10[:5,:]

(2000,)
(2000, 5)


array([[1, 0, 0, 0, 0],
       [1, 0, 0, 0, 0],
       [1, 0, 0, 0, 0],
       [1, 0, 0, 0, 0],
       [1, 0, 0, 0, 0]], dtype=uint8)

In [9]:
import tensorflow as tf

In [10]:
# Considering only 10 subjects


#preparing the data for training
from sklearn.model_selection import train_test_split

X_train = np.zeros((240*5,31))
y_train = np.zeros((240*5,5))
X_test = np.zeros((160*5,31))
y_test = np.zeros((160*5,5))

for i in range(1,6):
    #print((i-1)*400,400+(i-1)*400)
    a = X.iloc[(i-1)*400:400+(i-1)*400,:]
    b = y_10[(i-1)*400:400+(i-1)*400,:]
    X_tn, X_tt, y_tn, y_tt = train_test_split(a, b, test_size=0.4,random_state=42,shuffle=True)
    s = int(0.6*400)
    s1 = int(0.4*400)
    #print(y_tn)
    X_train[(i-1)*s:s+(i-1)*s,:] = X_tn
    y_train[(i-1)*s:s+(i-1)*s,:] = y_tn
    X_test[(i-1)*s1:s1+(i-1)*s1,:] = X_tt
    y_test[(i-1)*s1:s1+(i-1)*s1,:] = y_tt
    


print(X_train.shape)
print(y_train.shape)
print(X_test.shape)
print(y_test.shape)
i=2
#print(y_train[(i-1)*s:s+(i-1)*s,:])

0 400
[[1 0 0 0 0]
 [1 0 0 0 0]
 [1 0 0 0 0]
 ...
 [1 0 0 0 0]
 [1 0 0 0 0]
 [1 0 0 0 0]]
400 800
[[0 1 0 0 0]
 [0 1 0 0 0]
 [0 1 0 0 0]
 ...
 [0 1 0 0 0]
 [0 1 0 0 0]
 [0 1 0 0 0]]
800 1200
[[0 0 1 0 0]
 [0 0 1 0 0]
 [0 0 1 0 0]
 ...
 [0 0 1 0 0]
 [0 0 1 0 0]
 [0 0 1 0 0]]
1200 1600
[[0 0 0 1 0]
 [0 0 0 1 0]
 [0 0 0 1 0]
 ...
 [0 0 0 1 0]
 [0 0 0 1 0]
 [0 0 0 1 0]]
1600 2000
[[0 0 0 0 1]
 [0 0 0 0 1]
 [0 0 0 0 1]
 ...
 [0 0 0 0 1]
 [0 0 0 0 1]
 [0 0 0 0 1]]
(1200, 31)
(1200, 5)
(800, 31)
(800, 5)
[[0. 1. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 ...
 [0. 1. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 1. 0. 0. 0.]]


In [11]:
a.shape


(400, 31)

In [12]:
b.shape

(400, 5)

In [13]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense

model = Sequential() 

In [14]:

model.add( Dense(units=300, activation='relu', \
                 input_shape=(31,)))


model.add(Dense(units =5,activation="softmax"))

In [15]:
# compile the model
model.compile(loss='sparse_categorical_crossentropy',
              optimizer=tf.keras.optimizers.RMSprop(),
              metrics=['accuracy'])

In [16]:
model.summary()

Model: "sequential"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
dense (Dense)                (None, 300)               9600      
_________________________________________________________________
dense_1 (Dense)              (None, 5)                 1505      
Total params: 11,105
Trainable params: 11,105
Non-trainable params: 0
_________________________________________________________________


In [17]:
print (y_train.shape)
print (X_train.shape)

(1200, 5)
(1200, 31)


In [18]:
model.fit(X_train, y_train, epochs = 24, batch_size= 1)

Train on 1200 samples
Epoch 1/24
   1/1200 [..............................] - ETA: 1:19

ValueError: Shape mismatch: The shape of labels (received (5,)) should equal the shape of logits except for the last dimension (received (1, 5)).

In [59]:
X_train.shape

(1200, 31)